### PR TITLE
Merge 'development' into quests.

### PR DESCRIPTION
**Pull request by eternalcomet**
## Description

Merge 'development' into quests.
So that now supports 3.2 version.

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by keqing114514** [comment]
hi in 3.2 #28 Can you fix

**Comment by eternalcomet** [comment]
> hi in 3.2 #28 Can you fix

you can clone my branch and compile and test it.

**Comment by keqing114514** [comment]
> 

Wait a minute. I'll test it

**Comment by keqing114514** [comment]
> > hi in 3.2 #28 Can you fix
> 
> you can clone my branch and compile and test it.

The problem still exists, can you fix it?

**Comment by eternalcomet** [comment]
> > > hi in 3.2 #28 Can you fix
> > 
> > 
> > you can clone my branch and compile and test it.
> 
> The problem still exists, can you fix it?

I tried to fix.You can fetch my code and try again.

**Comment by keqing114514** [comment]
> 

thank

**Pull request closed without merging**
