### PR TITLE
Quest fix 357 (mainly 35722 Dvalin fight)

### PR DESCRIPTION
**Pull request by mjolsic**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
- Fixed Quest 357 Dvalin fight to be able to 
-- use missile skill
-- teleport back to world after defeating dvalin
-- advance quest to 358

- Known Issue
-- Using movement keys (W,A,S,D) in Dvalin fight might be kicked out of world
-- Weather is showing SUNNY after quest 35725 cutscene (should show storm or cloudy)

## Type of changes
https://youtu.be/vYJ2UYNwBB4?t=59

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by akatatsu27** [comment]
weather is managed completely server-side afaik. Client only informs the server of it's current areaID1 and areaID2 (which can be determined from sceneX_worldArea.json anyway) via EnterWorldAreaReq

**Comment by mjolsic** [comment]
I see. Thanks  for letting me know, will definitely look into that.

**Comment by keqing114514** [comment]
hi I want to use it in 3.2. Can you help me? I cannot use give all in 3.2

**Comment by thecutefinder** [comment]
@mjolsic Do you still have the original `.proto` files you used, prior to compilation/building?

**Comment by mjolsic** [comment]
> @mjolsic Do you still have the original `.proto` files you used, prior to compilation/building?

Im afraid I don't. Probably I can help you with other files if you'd be a little bit more specific on why you want them.

**Comment by Hartie95** [comment]
> @mjolsic Do you still have the original `.proto` files you used, prior to compilation/building?

You can probably get them from the Sorapointa protos repository. 

But keep in mind that upstream grasscutter is build for another client version, so you will need protos for that version.

**Comment by thecutefinder** [comment]
Ah, I see. Thanks to the both of you two though, and yes, I know that the upstream Grasscutter is for another version.

**Pull request merged**
